//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internautes
    {
        public int Id { get; set; }
        public int Note { get; set; }
        public string Commentaire { get; set; }
        public int ServiceId { get; set; }
    
        public virtual ServiceTouristiques ServiceTouristiques { get; set; }
    }
}
