//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTouristiques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceTouristiques()
        {
            this.Activites = new HashSet<Activites>();
            this.Buses = new HashSet<Buses>();
            this.Chambres = new HashSet<Chambres>();
            this.Internautes = new HashSet<Internautes>();
            this.Offres = new HashSet<Offres>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Description { get; set; }
        public string Anciennete { get; set; }
        public Nullable<int> busId { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> NombreEtoile { get; set; }
        public string Qualite { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string typeCuisine { get; set; }
        public string FraicheurDePlats { get; set; }
        public string Discriminator { get; set; }
        public Nullable<int> bus_Id { get; set; }
        public Nullable<int> localisation_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activites> Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buses> Buses { get; set; }
        public virtual Buses Buses1 { get; set; }
        public virtual Buses Buses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chambres> Chambres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Internautes> Internautes { get; set; }
        public virtual Localisations Localisations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offres> Offres { get; set; }
    }
}
